#端口配置
server:
  port: 8080
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys_user?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 2
  session:
    store-type: redis
    timeout: 1800000 #过期时间

mybatis:
  type-aliases-package: com.zhsw.sercuritydemo.entity
  mapper-locations: classpath:mapper/*.xml


